name = "gea-bizops"
compatibility_date = "2024-11-15"

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"

[env.dev]
name = "gea-bizops-dev"
route = { pattern = "bizops.dev.geadev.com/*", zone_name = "geadev.com" }
workers_dev = true
preview_urls = true

[env.staging]
name = "gea-bizops-staging"
route = { pattern = "bizops.gearmentinc.com/*", zone_name = "gearmentinc.com" }

[env.production]